const memes = [
    {
        id: "meme1",
        src: "img/cow.jpg",
        title: "Корова думает",
        description: "Ироничная корова в поле",
        tags: ["Животные", "Ирония"],
        year: 2021,
        source: "https://example.com/meme1",
        rating: 34,
    },
    {
        id: "meme2",
        src: "img/spring.jpg",
        title: "Весна 2028",
        description: "Встреча в 2028",
        tags: ["Абсурд", "Постирония"],
        year: 2020,
        source: "https://example.com/meme2",
        rating: 128,
    },
    {
        id: "meme3",
        src: "img/lion.jpg",
        title: "Лев в тачке",
        description: "Лев в тачке без удовольствия",
        tags: ["Абсурд", "Постирония", "Другие", "Животные"],
        year: 2020,
        source: "https://example.com/meme3",
        rating: 128,
    },
    {
        id: "meme4",
        src: "img/dog_fish.jpg",
        title: "Cон собаки",
        description: "Сон собаки про перевоплощение в рыбу",
        tags: ["Абсурд", "Постирония", "Собаки", "Животные"],
        year: 2020,
        source: "https://example.com/meme4",
        rating: 128,
    },
    {
        id: "meme5",
        src: "img/tarhun.jpg",
        title: "Тархун-комната",
        description: "Приглашение побывать в тархун-комнате",
        tags: ["Абсурд", "Постирония"],
        year: 2020,
        source: "https://example.com/meme5",
        rating: 128,
    },
    {
        id: "meme6",
        src: "img/yagami_lite.jpg",
        title: "Тест",
        description: "Ягами Лайт пишет тесты на 3",
        tags: ["Аниме"],
        year: 2020,
        source: "https://example.com/meme6",
        rating: 128,
    },
    {
        id: "meme7",
        src: "img/anime_humor.jpg",
        title: "Аниме юмор",
        description: "Аниме анегдоты",
        tags: ["Аниме"],
        year: 2020,
        source: "https://example.com/meme7",
        rating: 128,
    },
    {
        id: "meme8",
        src: "img/cat_shrimp.jpg",
        title: "Кот креветка",
        description: "Ешьте с осторожностью",
        tags: ["Абсурд", "Коты"],
        year: 2020,
        source: "https://example.com/meme8",
        rating: 128,
    },
    {
        id: "meme9",
        src: "img/kitty_fire.jpg",
        title: "Кот и огонь",
        description: "Кот на фоне пожара",
        tags: ["Коты", "Абсурд"],
        year: 2020,
        source: "https://example.com/meme9",
        rating: 128,
    },
    {
        id: "meme10",
        src: "img/qiwi.jpg",
        title: "Киви",
        description: "Мечты о том, чтобы стать киви",
        tags: ["Другие", "Сюрреализм"],
        year: 2019,
        source: "https://example.com/meme10",
        rating: 47,
    },
    {
        id: "meme11",
        src: "img/bread.jpg",
        title: "Хлеб",
        description: "Я тоже",
        tags: ["Абсурд", "Ирония"],
        year: 2021,
        source: "https://example.com/meme11",
        rating: 95,
    },
    {
        id: "meme12",
        src: "img/potato.jpg",
        title: "Картофель с тату",
        description: "Самовыражение - это важно",
        tags: ["Абсурд", "Ирония"],
        year: 2021,
        source: "https://example.com/meme12",
        rating: 95,
    },
    {
        id: "meme13",
        src: "img/tea_cat.jpg",
        title: "Чайный гриб",
        description: "Доставка по всей России",
        tags: ["Игры", "Аниме", "Абсурд"],
        year: 2021,
        source: "https://example.com/meme13",
        rating: 95,
    },
    {
        id: "meme14",
        src: "img/sheep.jpg",
        title: "Овцы и Excel",
        description: "Им повезло",
        tags: ["Другие", "Абсурд"],
        year: 2021,
        source: "https://example.com/meme14",
        rating: 95,
    },
    {
        id: "meme15",
        src: "img/vll.jpg",
        title: "Цикл",
        description: "Вот так",
        tags: ["Игры", "Аниме"],
        year: 2021,
        source: "https://example.com/meme15",
        rating: 95,
    },
    {
        id: "meme16",
        src: "img/buryat.jpg",
        title: "Бурятия тикток",
        description: "Грустно",
        tags: ["Аниме", "Региональные"],
        year: 2021,
        source: "https://example.com/meme16",
        rating: 95,
    },
    {
        id: "meme17",
        src: "img/princess.jpg",
        title: "Принцесса",
        description: "3 опция",
        tags: ["Игры", "Аниме"],
        year: 2021,
        source: "https://example.com/meme17",
        rating: 95,
    },
    {
        id: "meme18",
        src: "img/puzzle.jpg",
        title: "Кот-пазл",
        description: "Такая жизнь",
        tags: ["Абсурд", "Ирония", "Кошки"],
        year: 2021,
        source: "https://example.com/meme18",
        rating: 95,
    },
    {
        id: "meme19",
        src: "img/achive.jpg",
        title: "Мотивация",
        description: "Это правильно",
        tags: ["Постирония"],
        year: 2021,
        source: "https://example.com/meme19",
        rating: 95,
    },
    {
        id: "meme20",
        src: "img/shock.jpg",
        title: "Шок",
        description: "Вот это оценка",
        tags: ["Игры"],
        year: 2021,
        source: "https://example.com/meme20",
        rating: 95,
    },
    {
        id: "meme21",
        src: "img/aranar.jpg",
        title: "Аранары",
        description: "Джунгли - суровые условия",
        tags: ["Игры"],
        year: 2021,
        source: "https://example.com/meme21",
        rating: 95,
    },
    {
        id: "meme22",
        src: "img/shashki.jpg",
        title: "Лейка и шашки",
        description: "Однозначная победа",
        tags: ["Абсурд", "Ирония"],
        year: 2021,
        source: "https://example.com/meme22",
        rating: 95,
    },
    {
        id: "meme23",
        src: "img/kittie_bubbles.jpg",
        title: "Кот и пузыри",
        description: "Котенок играет с мыльными пузырями",
        tags: ["Коты", "Милота"],
        year: 2022,
        source: "https://example.com/meme23",
        rating: 88,
    },
    {
        id: "meme24",
        src: "img/cow_chuvash.jpg",
        title: "Чувашская корова",
        description: "Корова с традиционным головным убором",
        tags: ["Животные", "Культура"],
        year: 2023,
        source: "https://example.com/meme24",
        rating: 72,
    },
    {
        id: "meme25",
        src: "img/fish_fashion.jpg",
        title: "Карась модный",
        description: "Следит за трендами",
        tags: ["Другие", "Животные", "Абсурд"],
        year: 2021,
        source: "https://example.com/meme25",
        rating: 95,
    },
    {
        id: "meme26",
        src: "img/goat.jpg",
        title: "Козел с характером",
        description: "Козел, позирующий как босс",
        tags: ["Животные", "Ирония"],
        year: 2020,
        source: "https://example.com/meme26",
        rating: 39,
    },
    {
        id: "meme27",
        src: "img/machine.jpg",
        title: "Локальный запуск",
        description: "Герой пытается помочь",
        tags: ["IT-мемы"],
        year: 2025,
        source: "https://example.com/meme27",
        rating: 38,
    },
    {
        id: "meme28",
        src: "img/linux.jpg",
        title: "Лев и Linux",
        description: "Лев использует Linux без удовольствия",
        tags: ["Животные", "Ирония", "IT-мемы"],
        year: 2025,
        source: "https://example.com/meme28",
        rating: 38,
    },
    {
        id: "meme29",
        src: "img/cats.jpg",
        title: "Разные кошки",
        description: "Выбор однозначен",
        tags: ["Коты", "Юмор"],
        year: 2018,
        source: "https://example.com/meme29",
        rating: 103,
    },
    {
        id: "meme30",
        src: "img/sleepy_kitties.jpg",
        title: "Сонные котята",
        description: "Котята спят в милой кучке",
        tags: ["Коты", "Милота"],
        year: 2021,
        source: "https://example.com/meme30",
        rating: 95,
    },
    {
        id: "meme31",
        src: "img/bee_lion.jpg",
        title: "Пчелолев",
        description: "Кричит",
        tags: ["Другие", "Животные", "Абсурд"],
        year: 2021,
        source: "https://example.com/meme31",
        rating: 95,
    },
    {
        id: "meme32",
        src: "img/torrent_steam.jpg",
        title: "Торрент и стим",
        description: "Сложный выбор",
        tags: ["Игры"],
        year: 2021,
        source: "https://example.com/meme32",
        rating: 95,
    },
];