const memes = [
    {
        src: "img/cow.jpg",
        title: "Корова думает",
        description: "Ироничная корова в поле",
        tags: ["Животные", "Ирония"],
        year: 2021,
        source: "https://example.com/meme1",
        rating: 34,
    },
    {
        src: "img/kitty_fire.jpg",
        title: "Кот и огонь",
        description: "Кот на фоне пожара",
        tags: ["Коты", "Абсурд"],
        year: 2020,
        source: "https://example.com/meme2",
        rating: 128,
    },
    {
        src: "img/qiwi.jpg",
        title: "Киви-банкомат",
        description: "Киви, который выглядит как банкомат",
        tags: ["Другие", "Сюрреализм"],
        year: 2019,
        source: "https://example.com/meme3",
        rating: 47,
    },
    {
        src: "img/kittie_bubbles.jpg",
        title: "Кот и пузыри",
        description: "Котенок играет с мыльными пузырями",
        tags: ["Коты", "Милота"],
        year: 2022,
        source: "https://example.com/meme4",
        rating: 88,
    },
    {
        src: "img/cow_chuvash.jpg",
        title: "Чувашская корова",
        description: "Корова с традиционным головным убором",
        tags: ["Животные", "Культура"],
        year: 2023,
        source: "https://example.com/meme5",
        rating: 72,
    },
    {
        src: "img/goat.jpg",
        title: "Козел с характером",
        description: "Козел, позирующий как босс",
        tags: ["Животные", "Ирония"],
        year: 2020,
        source: "https://example.com/meme6",
        rating: 39,
    },
    {
        src: "img/cats.jpg",
        title: "Кошачья банда",
        description: "Группа котов, как будто собралась на собрание",
        tags: ["Коты", "Юмор"],
        year: 2018,
        source: "https://example.com/meme7",
        rating: 103,
    },
    {
        src: "img/sleepy_kitties.jpg",
        title: "Сонные котята",
        description: "Котята спят в милой кучке",
        tags: ["Коты", "Милота"],
        year: 2021,
        source: "https://example.com/meme8",
        rating: 95,
    },
];
